[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"


[dependencies]
chrono = "0.4"
digest = "0.9.0"
sha2 = "0.9.5"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
rocket = "0.5.0-rc.1"
